apiVersion: v1
kind: ConfigMap
metadata:
  name: speech-translate-config
data:
  BACKEND_URL: "http://speech-translate-backend:8080"
  ASSEMBLYAI_API_KEY: "74a758d1b3ef46608ad94e38060698ce"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: speech-translate-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: speech-translate-frontend
  template:
    metadata:
      labels:
        app: speech-translate-frontend
    spec:
      containers:
      - name: frontend
        image: speech-translate-frontend:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: speech-translate-config
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: speech-translate-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: speech-translate-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: speech-translate-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: speech-translate-backend
  template:
    metadata:
      labels:
        app: speech-translate-backend
    spec:
      containers:
      - name: backend
        image: speech-translate-backend:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: speech-translate-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: speech-translate-backend
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: speech-translate-backend